# Generated by Django 5.2.1 on 2025-05-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logoimg', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='로고이미지')),
                ('menu1', models.CharField(blank=True, max_length=20, null=True, verbose_name='메뉴1')),
                ('menu1_link', models.CharField(blank=True, max_length=20, null=True, verbose_name='메뉴1 url 네임')),
                ('menu2', models.CharField(blank=True, max_length=20, null=True, verbose_name='메뉴2')),
                ('menu2_link', models.CharField(blank=True, max_length=20, null=True, verbose_name='메뉴2 url 네임')),
                ('menu3', models.CharField(blank=True, max_length=20, null=True, verbose_name='메뉴3')),
                ('menu3_link', models.CharField(blank=True, max_length=20, null=True, verbose_name='메뉴3 url 네임')),
                ('menu4', models.CharField(blank=True, max_length=20, null=True, verbose_name='메뉴4')),
                ('menu4_link', models.CharField(blank=True, max_length=20, null=True, verbose_name='메뉴4 url 네임')),
                ('menu5', models.CharField(blank=True, max_length=20, null=True, verbose_name='메뉴5')),
                ('menu5_link', models.CharField(blank=True, max_length=20, null=True, verbose_name='메뉴5 url 네임')),
                ('menu6', models.CharField(blank=True, max_length=20, null=True, verbose_name='메뉴6')),
                ('menu6_link', models.CharField(blank=True, max_length=20, null=True, verbose_name='메뉴6 url 네임')),
            ],
            options={
                'verbose_name': '헤더',
                'verbose_name_plural': '헤더',
            },
        ),
    ]
