# Generated by Django 5.2.1 on 2025-05-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu1_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='메뉴1 url 네임'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu2_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='메뉴2 url 네임'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu3_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='메뉴3 url 네임'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu4_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='메뉴4 url 네임'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu5_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='메뉴5 url 네임'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu6_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='메뉴6 url 네임'),
        ),
    ]
