# Generated by Django 5.2.1 on 2025-05-09 16:27

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail1', models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='워크섬네일')),
                ('thumbnail2', models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='블로그섬네일')),
                ('is_index', models.BooleanField(default=False, verbose_name='메인페이지 게시 여부')),
                ('is_visible', models.BooleanField(default=False, verbose_name='노출 여부')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='본문 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '블로그',
                'verbose_name_plural': '블로그',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='작성자')),
                ('author_email', models.CharField(blank=True, max_length=200, null=True, verbose_name='작성자 이메일')),
                ('pw', models.CharField(blank=True, max_length=50, null=True, verbose_name='비밀번호')),
                ('content', models.TextField(verbose_name='댓글 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('is_visible', models.BooleanField(default=False, verbose_name='노출 여부')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '코멘트',
                'verbose_name_plural': '코멘트',
            },
        ),
    ]
