# Generated by Django 5.2.1 on 2025-05-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pop_words',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='메인페이지 팝 문구'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='블로그리스트 노출 여부'),
        ),
    ]
