# Generated by Django 5.2.1 on 2025-05-09 17:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='프로필사진')),
                ('name', models.CharField(blank=True, max_length=10, null=True, verbose_name='이름')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='나이')),
                ('major1', models.CharField(blank=True, max_length=20, null=True, verbose_name='대학원전공')),
                ('major2', models.CharField(blank=True, max_length=20, null=True, verbose_name='학부전공')),
                ('social', models.CharField(blank=True, max_length=20, null=True, verbose_name='소셜링크')),
                ('title', models.TextField(blank=True, null=True, verbose_name='제목')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='본문 내용')),
                ('ongoing_pl', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='진행중프로젝트 이미지')),
                ('is_active', models.BooleanField(default=False, verbose_name='활성여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '어바웃',
                'verbose_name_plural': '어바웃',
            },
        ),
    ]
