# Generated by Django 5.2.1 on 2025-05-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True, verbose_name='제목')),
                ('content', models.TextField(verbose_name='본문 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=False, verbose_name='활성여부')),
            ],
            options={
                'verbose_name': 'GPT프롬프트',
                'verbose_name_plural': 'GPT프롬프트',
            },
        ),
    ]
