# Generated by Django 5.2.1 on 2025-05-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='제목'),
        ),
    ]
