# Generated by Django 5.2.1 on 2025-05-10 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_agent_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agent',
            new_name='RAG',
        ),
    ]
