# Generated by Django 5.2.1 on 2025-05-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_rename_agent_rag'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConvHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('ask', models.TextField(blank=True, null=True, verbose_name='질문내용')),
                ('ip', models.CharField(blank=True, max_length=225, null=True, verbose_name='사용자ip')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='답변내용')),
                ('model', models.CharField(blank=True, max_length=225, null=True, verbose_name='LLM모델명')),
            ],
            options={
                'verbose_name': '방문자대화기록',
                'verbose_name_plural': '방문자대화기록',
            },
        ),
        migrations.DeleteModel(
            name='Prompt',
        ),
    ]
