# Generated by Django 5.2.1 on 2025-05-10 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_aiconvhistory_delete_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconvhistory',
            name='rag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='about.rag', verbose_name='RAG'),
        ),
    ]
