# Generated by Django 5.2.1 on 2025-05-10 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_aiconvhistory_rag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': '어바웃 페이지 설정', 'verbose_name_plural': '어바웃 페이지 설정'},
        ),
        migrations.AlterModelOptions(
            name='rag',
            options={'verbose_name': 'RAG', 'verbose_name_plural': 'RAG'},
        ),
    ]
